### ISSUE TITLE
Cannot Open File

### ISSUE THREAD

**Issue by ashcoft** [CADViewer/NextCloud#25]
![image](https://user-images.githubusercontent.com/1115854/225147351-faf6fdbf-7d20-4e38-8835-ae304397a271.png)
the file still cannot open.

**Comment by ashcoft** [comment]
![image](https://user-images.githubusercontent.com/1115854/225148023-bf610bd4-9dc1-4944-8a58-e8dca2dc9929.png)

**Comment by ashcoft** [comment]
Encryption is disabled but the file cannot be opened
![image](https://user-images.githubusercontent.com/1115854/232272049-cc48ed28-6387-4054-883f-2d6e1480e137.png)
![image](https://user-images.githubusercontent.com/1115854/232272062-7727ba1c-aef9-4fa4-bf34-aac5fdc878ff.png)

**Comment by CADViewer** [comment]
Hello @ashcoft , we briefly tested with encryption and it will never work, because the back-end converter requires the base DWG drawing to be un-encrypted. Even when then de-selecting encryption, the feeling was that the files on the server could not be handled, and we then reinstalled NextCloud,base version,  and uploaded fresh drawings for conversion and display.
