### ISSUE TITLE
Nothing display and without any error

### ISSUE THREAD

**Issue by kevinkuan1969** [CADViewer/NextCloud#42]
Nextcloud - 26.01
CADViewer - 8.63.3

Previously all files dwg, dwf, dxf can be opened in previous version but after upgrade to above version, nothing display and without any error.

I am not AutoCAD user and not familiar with all the new settings as below:
![image](https://user-images.githubusercontent.com/80019930/236116594-2ef86e86-0f23-4e65-b035-90bc4ed6d8f5.png)

My objective is to include AutoCAD viewer as part of the total solutions and hope you can help to make it available.
Here the login page - https://demo.analytic360.biz. 

Thansk.

**Comment by CADViewer** [comment]
Hello @kevinkuan1969 ,  the control parameters that are exposed are not related to the display of drawings, it's our more advanced conversion controls that users can use to make specific optimizations. 

Since the back-end converter has been updated, - and is being updated continously -, I think you probably need to run the settings script or to follow the https://github.com/CADViewer/NextCloud/blob/main/README.md  to change the permission of the executable.

We would be happy to take a look at your installation, if so, we need temporary access. Please write directly to developer@tailormade.com or casper.harnung@tailormade.com to continue, so you dont expose access credentials publicly. 

Thanks!

See below:  the login page did not allow for user access: 

![image](https://user-images.githubusercontent.com/61973235/236127396-a1df84e9-e49a-40d9-b28a-559b1fdb6b33.png)

**Comment by CADViewer** [comment]
Hi @kevinkuan1969 , I was able to log on now. I think you need to check item 4. under Troubleshooting,  you need to apply the rewrite rule, so that the URL pointing to icons, scripts, etc. can actually run on your system:   https://github.com/CADViewer/NextCloud#readme


![image](https://user-images.githubusercontent.com/61973235/236138909-39b84ea0-c77d-43c2-9655-0c008fde8ff6.png)

**Comment by kevinkuan1969** [comment]
Thanks and it works. It seems that the same steps need to be applied again for every new upgrade.

**Comment by johnny9798** [comment]
Hi, i have the same issue...
How can i add rewrite rules and rewrite condition if i use nginx reverse proxy ?

**Comment by johnny9798** [comment]
i have .htaccess error with CADViewer Doctor tool

**Comment by johnny9798** [comment]
@CADViewer need help please
