### ISSUE TITLE
DWG File is downloaded instead of being open .  

### ISSUE THREAD

**Issue by webdesign7** [CADViewer/NextCloud#80]
Hello, 

I have a fresh installation of NextCloud and Cadviewer ( also have OnlyOffice installed and working ) 

When I click on any DWF file it downloads it instead of opening it through the cadviewer app

However when I go an open any OnlyOffice document then after that the DWG file opens through the cadviewer app normally. 

Any ideas ? I want it to always open though the app instead of being downloaded 

Thanks

**Comment by CADViewer** [comment]
Hello @webdesign7 , we will try replicate and let you know!

**Comment by kevinkuan1969** [comment]
+1. Facing the same problem.

**Comment by lethargicpillow** [comment]
For me it happens from time to time, when I'm trying to open some really large drawing, or .dwg's containing 3D objects and closing the file before the "Loading..." pop-up disappears. After that, CadViewer kinda breaks and drawings begin to download instead of being open. What I've noticed: clicking the target folder name (where the path displayed graphically with arrows) helps to fix the issue (the transparent icon background becomes white after clicking as an indication).

**Comment by CADViewer** [comment]
Hi all, we found a method overlap with NC28, in a code section where NC28 sets up paths for loading application files.  We have rewritten code on our end,  please test with new CADViewer v9.44.2 and provide feedback. Thanks!

**Comment by CADViewer** [comment]
OK, update verified by user.
